name = "POE-Component-EasyDBI"
authors = ['David Davis <xantus@cpan.org>']
authority = "cpan:XANTUS"
license = "artistic_1"
readme_from = "lib/POE/Component/EasyDBI.pm"
abstract_from = "lib/POE/Component/EasyDBI.pm"
no_github_issues = true
